# Generated by Django 3.2 on 2022-02-20 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220219_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='img_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='reviews',
            field=models.ManyToManyField(to='todo.Review'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='website_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cost_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(blank=True, max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Sublease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
            ],
        ),
    ]
