# Generated by Django 3.2 on 2022-02-22 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='maintainence_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
