# Generated by Django 3.2 on 2022-02-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20220222_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='reviews',
        ),
        migrations.AddField(
            model_name='apartment',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.review'),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('img_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.address')),
                ('apartments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=120, unique=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.address')),
            ],
        ),
    ]
