# Generated by Django 3.2 on 2022-02-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20220223_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.apartment'),
        ),
    ]
