# Generated by Django 3.2 on 2022-02-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20220223_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='apartments',
        ),
        migrations.AddField(
            model_name='apartment',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.university'),
        ),
    ]
