# Generated by Django 3.2 on 2022-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
