# Generated by Django 3.2 on 2022-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublease',
            name='tenants',
            field=models.ManyToManyField(to='todo.User'),
        ),
    ]
