# Generated by Django 3.2 on 2022-03-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20220304_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
