# Generated by Django 4.0.3 on 2022-03-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_apartment_apartment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
