# Generated by Django 4.0.3 on 2022-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_apartment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantbuilding',
            name='university',
        ),
        migrations.AddField(
            model_name='sublease',
            name='sublease_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='university',
            name='important_buildings',
            field=models.ManyToManyField(to='todo.importantbuilding'),
        ),
    ]
