# Generated by Django 4.0.3 on 2022-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_remove_importantbuilding_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='address',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
