# Generated by Django 4.0.3 on 2022-03-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='apartments',
            field=models.ManyToManyField(null=True, to='todo.apartment'),
        ),
        migrations.AlterField(
            model_name='university',
            name='important_buildings',
            field=models.ManyToManyField(null=True, to='todo.importantbuilding'),
        ),
    ]
