# Generated by Django 4.0.3 on 2022-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_alter_university_apartments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='apartments',
            field=models.ManyToManyField(blank=True, to='todo.apartment'),
        ),
        migrations.AlterField(
            model_name='university',
            name='important_buildings',
            field=models.ManyToManyField(blank=True, to='todo.importantbuilding'),
        ),
    ]
