# Generated by Django 4.0.3 on 2022-03-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_importantbuilding_building_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantbuilding',
            name='nearby_apartments',
            field=models.ManyToManyField(blank=True, to='todo.apartment'),
        ),
    ]
