# Generated by Django 4.0.3 on 2022-03-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_importantbuilding_nearby_apartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='cost',
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='apartment',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
