# Generated by Django 4.0.3 on 2022-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_remove_apartment_cost_apartment_max_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
