# Generated by Django 4.0.3 on 2022-03-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_remove_review_likes_review_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('corresponding_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.review')),
            ],
        ),
    ]
