# Generated by Django 4.0.3 on 2022-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
