# Generated by Django 4.0.3 on 2022-03-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0042_user_last_login_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
