# Generated by Django 4.0.3 on 2022-03-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0046_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
