# Generated by Django 4.0.3 on 2022-03-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0047_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
