# Generated by Django 4.0.3 on 2022-03-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0048_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
