# Generated by Django 4.0.3 on 2022-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0049_remove_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
