# Generated by Django 4.0.3 on 2022-04-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0050_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
