# Generated by Django 4.0.3 on 2022-04-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0052_review_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublease',
            name='tenants',
        ),
        migrations.AddField(
            model_name='sublease',
            name='tenants',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
        ),
    ]
