# Generated by Django 4.0.3 on 2022-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0054_rename_tenants_sublease_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
