# Generated by Django 4.0.3 on 2022-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0058_alter_review_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='review_text_val',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
