# Generated by Django 4.0.3 on 2022-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0060_rename_review_text_val_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
