# Generated by Django 4.0.3 on 2022-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0064_remove_review_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
