# Generated by Django 4.0.3 on 2022-04-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0065_review_review_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
