# Generated by Django 4.0.3 on 2022-04-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0066_delete_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublease',
            name='associated_apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.apartment'),
        ),
        migrations.AlterField(
            model_name='sublease',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
        ),
    ]
