# Generated by Django 4.0.3 on 2022-04-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0067_alter_sublease_associated_apartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentSublease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublease_text', models.TextField(default='')),
                ('associated_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Sublease',
        ),
    ]
