# Generated by Django 4.0.3 on 2022-04-22 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0068_apartmentsublease_delete_sublease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review_text', models.TextField(blank=True, max_length=2048, null=True)),
                ('cost_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('maintainence_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('quietness_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('cleanliness_rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='todo.user')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='todo.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
