# Generated by Django 4.0.4 on 2023-01-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0073_apartment_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('walking_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('biking_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('driving_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
                ('important_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.importantbuilding')),
            ],
        ),
    ]
