# Generated by Django 4.0.4 on 2023-01-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0074_distancematrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancematrix',
            name='transit_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='biking_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='driving_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='walking_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
