# Generated by Django 4.0.4 on 2023-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0075_distancematrix_transit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancematrix',
            name='transit_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
