# Generated by Django 4.0.4 on 2023-01-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0076_alter_distancematrix_transit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distancematrix',
            old_name='distance',
            new_name='straight_distance',
        ),
        migrations.RemoveField(
            model_name='distancematrix',
            name='transit_time',
        ),
    ]
