# Generated by Django 4.0.4 on 2023-01-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0077_rename_distance_distancematrix_straight_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMatrixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('walking_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('biking_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('driving_distance', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.apartment')),
                ('important_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.importantbuilding')),
            ],
        ),
    ]
