# Generated by Django 4.0.4 on 2023-01-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0078_distancematrixmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistanceMatrix',
        ),
    ]
