# Generated by Django 3.2 on 2022-03-01 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b748d362-a43b-4bb3-9978-dc59be7689af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
