# Generated by Django 3.2 on 2022-03-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_sublease_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='university',
        ),
        migrations.AddField(
            model_name='importantbuilding',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='apartments',
            field=models.ManyToManyField(to='todo.Apartment'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
