# Generated by Django 4.0.3 on 2022-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_alter_university_apartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantbuilding',
            name='building_slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
