# Generated by Django 4.0.3 on 2022-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
