# Generated by Django 4.0.3 on 2022-03-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0039_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
