# Generated by Django 4.0.3 on 2022-04-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0053_remove_sublease_tenants_sublease_tenants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublease',
            old_name='tenants',
            new_name='tenant',
        ),
    ]
