# Generated by Django 4.0.3 on 2022-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0056_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
