# Generated by Django 4.0.3 on 2022-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0070_apartmentsublease_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsublease',
            name='baths',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartmentsublease',
            name='beds',
            field=models.IntegerField(default=1),
        ),
    ]
