# Generated by Django 4.0.3 on 2022-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0071_apartmentsublease_baths_apartmentsublease_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
